services:
  postgres:
    image: postgres:16-alpine
    container_name: telegram-movie-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_movie
    volumes:
      - telegram_movie_pg:/var/lib/postgresql/data

volumes:
  telegram_movie_pg:
