export const ErrorCodes = {
  MOVIE_NOT_FOUND: 'MOVIE_NOT_FOUND',
  SEASON_NOT_FOUND: 'SEASON_NOT_FOUND',
  EPISODE_NOT_FOUND: 'EPISODE_NOT_FOUND',
  INVALID_TELEGRAM_AUTH: 'INVALID_TELEGRAM_AUTH',
  TELEGRAM_AUTH_EXPIRED: 'TELEGRAM_AUTH_EXPIRED',
  PLAYBACK_SOURCE_FAILED: 'PLAYBACK_SOURCE_FAILED',
  TELEGRAM_FILE_NOT_FOUND: 'TELEGRAM_FILE_NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ADMIN_UNAUTHORIZED: 'ADMIN_UNAUTHORIZED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
